// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeBuddy.Service.Contexts;

#nullable disable

namespace TimeBuddy.Service.Migrations
{
    [DbContext(typeof(TimeBuddyContext))]
    partial class TimeBuddyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeBuddy.Service.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeBuddy.Service.Models.ProjectSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<double>("TargetHoursPerDay")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectSettings");
                });

            modelBuilder.Entity("TimeBuddy.Service.Models.TimeFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TimeFrames");
                });

            modelBuilder.Entity("TimeBuddy.Service.Models.ProjectSettings", b =>
                {
                    b.HasOne("TimeBuddy.Service.Models.Project", "Project")
                        .WithOne("Settings")
                        .HasForeignKey("TimeBuddy.Service.Models.ProjectSettings", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeBuddy.Service.Models.TimeFrame", b =>
                {
                    b.HasOne("TimeBuddy.Service.Models.Project", null)
                        .WithMany("TimeFrames")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("TimeBuddy.Service.Models.Project", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("TimeFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
